/**
 * @file WMLCaptivePortal.cpp
 * @brief Implementation of Captive Portal for WiFiManagerLite
 * 
 * Uses GZIP-compressed web assets generated by tools/build_webui.py
 * 
 * @author Extracted from BambuBeacon project
 * @version 2.0.0
 */

#include "WMLCaptivePortal.h"
#include "WMLBuildConfig.h"
#include "generated/wml_web_manifest.h"

#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <ArduinoJson.h>
#include <esp_timer.h>

namespace WML {

// ==================== Restart Helper ====================

static void wml_restart_callback(void* arg) {
    (void)arg;
    ESP.restart();
}

// ==================== Constructor ====================

CaptivePortal::CaptivePortal(AsyncWebServer& server, WiFiManagerLite& wifiManager)
    : _server(server)
    , _wifiManager(wifiManager)
    , _onConfigChange(nullptr)
    , _onConfigGet(nullptr)
    , _onFactoryReset(nullptr)
    , _onWiFiReset(nullptr)
    , _authUser(WML_WEB_AUTH_USER)
    , _authPass(WML_WEB_AUTH_PASS)
    , _deviceName(WML_DEFAULT_DEVICE_NAME)
    , _firmwareVersion(WML_FIRMWARE_VERSION)
    , _restartAfterSave(true)  // Default: restart after save
    , _scanCount(0)
    , _scanRunning(false)
    , _scanCacheTime(0)
    , _lastRequestTime(0)
    , _pendingReset(false)
    , _pendingFactoryReset(false)
    , _pendingResetTime(0)
    , _statusContributorCount(0)
    , _routeRegistrarCount(0)
    , _configProviderCount(0)
    , _loopHandlerCount(0)
{
    memset(_scanCache, 0, sizeof(_scanCache));
    memset(_statusContributors, 0, sizeof(_statusContributors));
    memset(_routeRegistrars, 0, sizeof(_routeRegistrars));
    memset(_configProviders, 0, sizeof(_configProviders));
    memset(_loopHandlers, 0, sizeof(_loopHandlers));
}

// ==================== Configuration ====================

void CaptivePortal::onConfigChange(ConfigChangeCallback callback) {
    _onConfigChange = callback;
}

void CaptivePortal::onConfigGet(ConfigGetCallback callback) {
    _onConfigGet = callback;
}

void CaptivePortal::onFactoryReset(std::function<void()> callback) {
    _onFactoryReset = callback;
}

void CaptivePortal::onWiFiReset(std::function<void()> callback) {
    _onWiFiReset = callback;
}

// setLogger() is now inline no-op in header - use WML_ENABLE_DEBUG_LOGS instead

void CaptivePortal::setAuthentication(const String& username, const String& password) {
    _authUser = username;
    _authPass = password;
}

void CaptivePortal::setDeviceName(const String& name) {
    _deviceName = name;
    _deviceNameExplicit = true;
}

void CaptivePortal::setFirmwareVersion(const String& version) {
    _firmwareVersion = version;
}

void CaptivePortal::setRestartAfterSave(bool restart) {
    _restartAfterSave = restart;
}

// ==================== Extension Points ====================

bool CaptivePortal::addStatusContributor(IStatusContributor* contributor) {
    if (!contributor) return false;
    if (_statusContributorCount >= kMaxExtensions) {
        WML_ERROR("StatusContributor registry full (max 8)");
        return false;
    }
    _statusContributors[_statusContributorCount++] = contributor;
    return true;
}

bool CaptivePortal::addRouteRegistrar(IRouteRegistrar* registrar) {
    if (!registrar) return false;
    if (_routeRegistrarCount >= kMaxExtensions) {
        WML_ERROR("RouteRegistrar registry full (max 8)");
        return false;
    }
    _routeRegistrars[_routeRegistrarCount++] = registrar;
    return true;
}

bool CaptivePortal::addConfigProvider(IConfigSectionProvider* provider) {
    if (!provider) return false;
    if (_configProviderCount >= kMaxExtensions) {
        WML_ERROR("ConfigProvider registry full (max 8)");
        return false;
    }
    _configProviders[_configProviderCount++] = provider;
    return true;
}

bool CaptivePortal::addLoopHandler(ILoopHandler* handler) {
    if (!handler) return false;
    if (_loopHandlerCount >= kMaxExtensions) {
        WML_ERROR("LoopHandler registry full (max 8)");
        return false;
    }
    _loopHandlers[_loopHandlerCount++] = handler;
    return true;
}

// ==================== Lifecycle ====================

void CaptivePortal::begin() {
    // If user didn't explicitly set a portal name, use WiFiManagerLite identity base name
    // (without MAC) for UI branding.
    if (!_deviceNameExplicit) {
        const String base = _wifiManager.getIdentityBaseName();
        if (base.length() > 0) {
            _deviceName = base;
        }
    }
    registerRoutes();
    WML_LOG_PORTAL("Captive Portal initialized (build: " WML_BUILD_HASH ")");
}

void CaptivePortal::loop() {
    // Collect scan results if available
    collectScanResults();
    
    // Handle pending resets (delayed to allow HTTP response to be sent)
    if (_pendingReset && (millis() - _pendingResetTime) >= kResetDelayMs) {
        _pendingReset = false;
        WML_LOG_PORTAL("Executing delayed WiFi reset");
        
        // Call user callback to clear credentials (if set)
        if (_onWiFiReset) {
            _onWiFiReset();
        }
        
        _wifiManager.reset();
    }
    
    if (_pendingFactoryReset && (millis() - _pendingResetTime) >= kResetDelayMs) {
        _pendingFactoryReset = false;
        WML_LOG_PORTAL("Executing delayed factory reset (with restart)");
        _wifiManager.factoryReset(_onFactoryReset, true);  // Always restart from web
    }
    
    // Call registered loop handlers
    for (uint8_t i = 0; i < _loopHandlerCount; i++) {
        if (_loopHandlers[i]) {
            _loopHandlers[i]->loop();
        }
    }
}

// ==================== Status ====================

bool CaptivePortal::hasActiveClients() const {
    return (millis() - _lastRequestTime) < kClientTimeoutMs;
}

// ==================== Route Registration ====================

void CaptivePortal::registerRoutes() {
    // Main setup page
    _server.on("/", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleRoot(request);
    });
    
    // Setup page (GZIP compressed)
    _server.on("/wml/setup", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleWiFiSetup(request);
    });
    
    // Stylesheet (GZIP compressed) - both variants
    _server.on("/wml/style.css", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleStyle(request);
    });
    
    // JavaScript (GZIP compressed) - both variants
    _server.on("/wml/app.js", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleScript(request);
    });
    
#if WML_PORTAL_VARIANT == WML_PORTAL_ADVANCED
    // Status page (GZIP compressed) - Advanced only
    _server.on("/wml/status", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleStatusPage(request);
    });
    
    // API: Status JSON - Advanced only
    _server.on("/wml/status.json", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleStatusJson(request);
    });
#endif
    
    // API: Network list
    _server.on("/wml/netlist", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleNetworkList(request);
    });
    
    // API: Config get
    _server.on("/wml/config", HTTP_GET, [this](AsyncWebServerRequest* request) {
        handleNetworkConfig(request);
    });
    
    // API: Config submit
    _server.on("/wml/submit", HTTP_POST, [this](AsyncWebServerRequest* request) {
        handleSubmitConfig(request);
    });
    
    // Reset endpoint
    _server.on("/wml/reset", HTTP_POST, [this](AsyncWebServerRequest* request) {
        _lastRequestTime = millis();
        if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
            return request->requestAuthentication();
        }
        WML_LOG_PORTAL("Reset requested via web");
        request->send(200, "application/json", "{\"success\":true}");
        // Delay reset to allow response to be sent
        _pendingReset = true;
        _pendingResetTime = millis();
    });
    
    // Factory reset endpoint
    _server.on("/wml/factoryreset", HTTP_POST, [this](AsyncWebServerRequest* request) {
        _lastRequestTime = millis();
        if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
            return request->requestAuthentication();
        }
        WML_LOG_PORTAL("Factory reset requested via web");
        request->send(200, "application/json", "{\"success\":true}");
        // Delay factory reset to allow response to be sent
        _pendingFactoryReset = true;
        _pendingResetTime = millis();
    });
    
    // Captive portal detection endpoints
    const char* captiveEndpoints[] = {
        "/generate_204",        // Android
        "/gen_204",             // Android
        "/hotspot-detect.html", // iOS
        "/library/test/success.html", // iOS
        "/ncsi.txt",            // Windows
        "/connecttest.txt",     // Windows
        "/fwlink"               // Windows
    };
    
    for (const char* endpoint : captiveEndpoints) {
        _server.on(endpoint, HTTP_GET, [this](AsyncWebServerRequest* request) {
            handleCaptivePortal(request);
        });
    }
    
    // 404 handler - redirect to setup in AP mode
    _server.onNotFound([this](AsyncWebServerRequest* request) {
        handleNotFound(request);
    });
    
    // Call registered route registrars (extension point)
    for (uint8_t i = 0; i < _routeRegistrarCount; i++) {
        if (_routeRegistrars[i]) {
            _routeRegistrars[i]->registerRoutes(_server);
        }
    }
}

// ==================== Request Handlers ====================

void CaptivePortal::handleRoot(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (_wifiManager.isAPMode()) {
        request->redirect("/wml/setup");
        return;
    }
    
    if (!isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // When connected, redirect to status page
    request->redirect("/wml/status");
}

void CaptivePortal::handleWiFiSetup(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    // In AP mode, no authentication required
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // NOTE: No scan here - JavaScript will call /wml/netlist which triggers scan
    // This prevents double-scanning on page load
    
    // Send GZIP compressed setup page (variant-dependent)
    sendGzipAsset(request, getSetupPageData(), getSetupPageLen(), "text/html", 300);
}

void CaptivePortal::handleStyle(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    // Send GZIP compressed stylesheet (variant-dependent)
    sendGzipAsset(request, getStyleData(), getStyleLen(), "text/css", 86400);
}

void CaptivePortal::handleScript(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    // Send GZIP compressed JavaScript (variant-dependent)
    sendGzipAsset(request, getAppJsData(), getAppJsLen(), "application/javascript", 86400);
}

#if WML_PORTAL_VARIANT == WML_PORTAL_ADVANCED

void CaptivePortal::handleStatusPage(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // Send GZIP compressed status page
    sendGzipAsset(request, wml_status_html_data, wml_status_html_len, "text/html", 300);
}

void CaptivePortal::handleStatusJson(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // HEAP-OPTIMIERT: WiFi-Strings einmal abrufen (vorher: 3 String-Allokationen pro Request)
    char ssidBuf[33];
    char ipBuf[16];
    char macBuf[18];
    
    // SSID einmal abrufen
    String tmpSsid = WiFi.SSID();
    strncpy(ssidBuf, tmpSsid.c_str(), sizeof(ssidBuf) - 1);
    ssidBuf[sizeof(ssidBuf) - 1] = '\0';
    
    // IP direkt formatieren (kein toString())
    IPAddress ip = WiFi.localIP();
    snprintf(ipBuf, sizeof(ipBuf), "%d.%d.%d.%d", ip[0], ip[1], ip[2], ip[3]);
    
    // MAC einmal abrufen
    String tmpMac = WiFi.macAddress();
    strncpy(macBuf, tmpMac.c_str(), sizeof(macBuf) - 1);
    macBuf[sizeof(macBuf) - 1] = '\0';
    
    // Use StaticJsonDocument + ResponseStream (no String allocation)
    // Larger buffer to accommodate extension contributions
    StaticJsonDocument<1024> doc;
    doc["connected"] = _wifiManager.isConnected();
    doc["ssid"] = ssidBuf;              // char* direkt, ArduinoJson kopiert nicht
    doc["ip"] = ipBuf;                  // char* direkt
    doc["rssi"] = WiFi.RSSI();
    doc["mac"] = macBuf;                // char* direkt
    doc["hostname"] = _deviceName.c_str();  // .c_str() vermeidet String-Kopie
    doc["uptime"] = millis() / 1000;
    doc["heap"] = ESP.getFreeHeap();
    doc["version"] = _firmwareVersion.c_str();
    doc["apMode"] = _wifiManager.isAPMode();
    
    // Call registered status contributors (extension point)
    for (uint8_t i = 0; i < _statusContributorCount; i++) {
        if (_statusContributors[i]) {
            _statusContributors[i]->contribute(doc);
        }
    }
    
    // Stream JSON directly to response (no intermediate String)
    AsyncResponseStream* response = request->beginResponseStream("application/json");
    serializeJson(doc, *response);
    request->send(response);
}

#endif // WML_PORTAL_ADVANCED

void CaptivePortal::handleNetworkList(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // Collect any finished scan results first
    collectScanResults();
    
    // Start new scan if cache is old
    startAsyncScan(false);
    
    // Stream JSON directly from struct cache (no intermediate String)
    // Size: ~100 bytes per network + overhead
    StaticJsonDocument<64 + kMaxScanNets * 100> doc;
    JsonArray networks = doc.createNestedArray("networks");
    
    if (_scanCacheTime > 0 && (millis() - _scanCacheTime) < kScanCacheMs) {
        // Build JSON directly from struct cache
        for (uint8_t i = 0; i < _scanCount; i++) {
            JsonObject net = networks.createNestedObject();
            net["ssid"] = _scanCache[i].ssid;
            net["rssi"] = _scanCache[i].rssi;
            net["enc"] = (_scanCache[i].encrypted != 0);
            net["bssid"] = _scanCache[i].bssid;
        }
    }
    
        doc["scanning"] = _scanRunning || (WiFi.scanComplete() == WIFI_SCAN_RUNNING);
    
    // Stream to response
    AsyncResponseStream* response = request->beginResponseStream("application/json");
    serializeJson(doc, *response);
    request->send(response);
}

void CaptivePortal::handleNetworkConfig(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // Use StaticJsonDocument + ResponseStream (no String allocation)
    // Larger buffer to accommodate extension contributions
    StaticJsonDocument<1024> doc;
    
    if (_onConfigGet) {
        Config cfg = _onConfigGet();
        doc["deviceName"] = cfg.deviceName;
        doc["ssid0"] = cfg.primary.ssid;
        doc["pass0"] = cfg.primary.password;
        doc["bssid0"] = cfg.primary.bssid;
        doc["bssidLock"] = cfg.primary.bssidLock;
        doc["ssid1"] = cfg.secondary.ssid;
        doc["pass1"] = cfg.secondary.password;
        doc["ip"] = cfg.staticIP.ip;
        doc["subnet"] = cfg.staticIP.subnet;
        doc["gateway"] = cfg.staticIP.gateway;
        doc["dns"] = cfg.staticIP.dns;
    } else {
        doc["deviceName"] = _deviceName;
        doc["ssid0"] = "";
        doc["pass0"] = "";
        doc["bssid0"] = "";
        doc["bssidLock"] = false;
        doc["ssid1"] = "";
        doc["pass1"] = "";
        doc["ip"] = "";
        doc["subnet"] = "";
        doc["gateway"] = "";
        doc["dns"] = "";
    }
    
    // Call registered config providers (extension point)
    for (uint8_t i = 0; i < _configProviderCount; i++) {
        if (_configProviders[i]) {
            _configProviders[i]->contributeConfig(doc);
        }
    }
    
    // Stream to response
    AsyncResponseStream* response = request->beginResponseStream("application/json");
    serializeJson(doc, *response);
    request->send(response);
}

void CaptivePortal::handleSubmitConfig(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (!_wifiManager.isAPMode() && !isAuthenticated(request)) {
        return request->requestAuthentication();
    }
    
    // Helper Lambda für Parameter-Abruf
    auto getParam = [request](const char* name) -> String {
        if (!request->hasParam(name, true)) return "";
        return request->getParam(name, true)->value();
    };
    
    // Build new configuration (char[] mit Setter-Methoden)
    Config newConfig;
    newConfig.setDeviceName(getParam("devicename"));
    newConfig.primary.setSsid(getParam("ssid0"));
    newConfig.primary.setPassword(getParam("password0"));
    newConfig.primary.setBssid(getParam("bssid0"));
    newConfig.primary.bssidLock = (getParam("bssidLock") == "1");
    newConfig.secondary.setSsid(getParam("ssid1"));
    newConfig.secondary.setPassword(getParam("password1"));
    newConfig.staticIP.setIp(getParam("ip"));
    newConfig.staticIP.setSubnet(getParam("subnet"));
    newConfig.staticIP.setGateway(getParam("gateway"));
    newConfig.staticIP.setDns(getParam("dns"));
    
    // Preserve existing settings not in form
    if (_onConfigGet) {
        Config existing = _onConfigGet();
        newConfig.ap = existing.ap;
        newConfig.timing = existing.timing;
        newConfig.enableMDNS = existing.enableMDNS;
        newConfig.httpPort = existing.httpPort;
    }
    
    WML_LOGF_PORTAL("Config submitted: SSID=%s", newConfig.primary.ssid);  // char[] direkt
    
    // Call callback if set
    bool accepted = true;
    if (_onConfigChange) {
        accepted = _onConfigChange(newConfig);
    }
    
    if (accepted) {
        // Send GZIP compressed success page (from webui_src/)
        if (_restartAfterSave) {
            sendGzipAsset(request, getSuccessRestartData(), getSuccessRestartLen(), "text/html", 0);
            WML_LOG_PORTAL("Config saved, restarting in 600ms...");
            scheduleRestart(WML_RESTART_DELAY_MS);
        } else {
            sendGzipAsset(request, getSuccessData(), getSuccessLen(), "text/html", 0);
            WML_LOG_PORTAL("Config saved (no restart)");
        }
    } else {
        sendGzipAsset(request, getErrorData(), getErrorLen(), "text/html", 0);
    }
}

void CaptivePortal::handleCaptivePortal(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (_wifiManager.isAPMode()) {
        handleWiFiSetup(request);
    } else {
        request->send(404, "text/plain", "Not found");
    }
}

void CaptivePortal::handleNotFound(AsyncWebServerRequest* request) {
    _lastRequestTime = millis();
    
    if (_wifiManager.isAPMode()) {
        request->redirect("/wml/setup");
    } else {
        request->send(404, "text/plain", "Not found");
    }
}

// ==================== Helper Methods ====================

void CaptivePortal::sendGzipAsset(AsyncWebServerRequest* request, 
                                   const uint8_t* data, size_t len, 
                                   const char* contentType, uint32_t cacheSeconds) {
    // HEAP-OPTIMIERT: Header-Prüfung mit minimaler String-Nutzung
    // (vorher: 2 String-Variablen pro Asset-Request)
    
    // Check if client accepts gzip - direkte Prüfung ohne lokale Variable
    bool acceptsGzip = false;
    if (request->hasHeader("Accept-Encoding")) {
        // Direkt auf Rückgabewert prüfen, keine lokale Kopie speichern
        acceptsGzip = request->header("Accept-Encoding").indexOf("gzip") >= 0;
    }
    
    // Build ETag and Cache-Control with stack buffers (no String concat)
    char etagBuf[64];
    snprintf(etagBuf, sizeof(etagBuf), "\"%s\"", WML_BUILD_HASH);
    char cacheBuf[48];
    snprintf(cacheBuf, sizeof(cacheBuf), "public, max-age=%lu", (unsigned long)cacheSeconds);

    // ETag-Vergleich - direkte Prüfung ohne lokale Variable
    if (request->hasHeader("If-None-Match")) {
        if (request->header("If-None-Match") == etagBuf) {
            request->send(304);
            return;
        }
    }

    if (acceptsGzip) {
        AsyncWebServerResponse* response = request->beginResponse_P(
            200, contentType, data, len
        );
        response->addHeader("Content-Encoding", "gzip");
        response->addHeader("ETag", etagBuf);
        response->addHeader("Cache-Control", cacheBuf);
        request->send(response);
    } else {
        AsyncWebServerResponse* response = request->beginResponse_P(
            200, contentType, data, len
        );
        response->addHeader("Content-Encoding", "gzip");
        response->addHeader("ETag", etagBuf);
        response->addHeader("Cache-Control", cacheBuf);
        request->send(response);
    }
}

bool CaptivePortal::isAuthenticated(AsyncWebServerRequest* request) {
    if (_authUser.length() == 0) {
        return true; // No auth configured
    }
    return request->authenticate(_authUser.c_str(), _authPass.c_str());
}

void CaptivePortal::scheduleRestart(uint32_t delayMs) {
    esp_timer_handle_t timer = nullptr;
    esp_timer_create_args_t args = {};
    args.callback = &wml_restart_callback;
    args.arg = nullptr;
    args.dispatch_method = ESP_TIMER_TASK;
    args.name = "wml_restart";
    
    if (esp_timer_create(&args, &timer) == ESP_OK && timer) {
        esp_timer_start_once(timer, (uint64_t)delayMs * 1000ULL);
    } else {
        // Fallback: immediate restart
        ESP.restart();
    }
}

void CaptivePortal::startAsyncScan(bool force) {
    // Check cache validity
    if (!force && _scanCacheTime > 0 && (millis() - _scanCacheTime) < kScanCacheMs) {
        return;
    }
    
    int scanStatus = WiFi.scanComplete();
    
    // If scan is running, just mark it
    if (scanStatus == WIFI_SCAN_RUNNING) {
        _scanRunning = true;
        return;
    }
    
    // If we have results, collect them first
    if (scanStatus >= 0) {
        collectScanResults();
    }
    
    // Start new scan
    WML_LOG_PORTAL("Starting WiFi scan...");
    WiFi.scanDelete();
    int result = WiFi.scanNetworks(true /* async */, true /* showHidden */);
    _scanRunning = (result == WIFI_SCAN_RUNNING);
    
    if (_scanRunning) {
        WML_LOG_PORTAL("Scan started (async)");
    } else {
        WML_LOGF_PORTAL("Scan failed to start: %d", result);
    }
}

void CaptivePortal::collectScanResults() {
    int count = WiFi.scanComplete();
    
    if (count == WIFI_SCAN_RUNNING) {
        _scanRunning = true;
        return;
    }
    
    if (count < 0) {
        _scanRunning = false;
        return;
    }
    
    _scanRunning = false;
    
    WML_LOGF_PORTAL("Scan complete: %d networks found", count);

    _scanCount = 0;
    const uint8_t maxNets = (count > kMaxScanNets) ? kMaxScanNets : static_cast<uint8_t>(count);

    // Reuse two Strings in the loop to avoid 40 separate heap allocations (heap-friendly)
    String tmpSsid;
    String tmpBssid;
    for (uint8_t i = 0; i < maxNets; i++) {
        tmpSsid = WiFi.SSID(i);
        strncpy(_scanCache[i].ssid, tmpSsid.c_str(), sizeof(_scanCache[i].ssid) - 1);
        _scanCache[i].ssid[sizeof(_scanCache[i].ssid) - 1] = '\0';

        tmpBssid = WiFi.BSSIDstr(i);
        strncpy(_scanCache[i].bssid, tmpBssid.c_str(), sizeof(_scanCache[i].bssid) - 1);
        _scanCache[i].bssid[sizeof(_scanCache[i].bssid) - 1] = '\0';

        _scanCache[i].rssi = WiFi.RSSI(i);
        _scanCache[i].encrypted = (WiFi.encryptionType(i) != WIFI_AUTH_OPEN) ? 1 : 0;
        _scanCount++;
    }
    
    WiFi.scanDelete();
    _scanCacheTime = millis();
}

// log() removed - using WML_LOG_PORTAL/WML_LOGF_PORTAL macros instead
// See WMLDebugLog.h for compile-time debug control

} // namespace WML
