/**
 * @file WMLCaptivePortal.h
 * @brief Captive Portal with Web UI for WiFiManagerLite
 * 
 * Provides a complete web-based configuration interface:
 * - WiFi network scanning and selection
 * - Primary and fallback SSID configuration
 * - Static IP configuration
 * - BSSID lock option
 * - Beautiful dark theme UI (GZIP compressed)
 * 
 * Web assets are generated by tools/build_webui.py from webui_src/
 * 
 * Requires ESPAsyncWebServer library.
 * 
 * @author Extracted from BambuBeacon project
 * @version 2.0.0
 */

#pragma once

#include <Arduino.h>
#include <functional>
#include "WMLBuildConfig.h"
#include "WMLDebugLog.h"
#include "WiFiManagerLite.h"
#include "WMLPortalExtensions.h"

// Forward declarations
class AsyncWebServer;
class AsyncWebServerRequest;

namespace WML {

/**
 * @brief Callback for configuration changes
 * @param config The new configuration
 * @return true to accept and apply, false to reject
 */
using ConfigChangeCallback = std::function<bool(const Config& config)>;

/**
 * @brief Callback for providing current configuration to the portal
 * @return Current configuration
 */
using ConfigGetCallback = std::function<Config()>;

/**
 * @brief Captive Portal with embedded Web UI (GZIP compressed)
 */
class CaptivePortal {
public:
    /**
     * @brief Constructor
     * @param server Reference to AsyncWebServer instance
     * @param wifiManager Reference to WiFiManagerLite instance
     */
    CaptivePortal(AsyncWebServer& server, WiFiManagerLite& wifiManager);
    
    /**
     * @brief Destructor
     */
    ~CaptivePortal() = default;
    
    // ==================== Configuration ====================
    
    /**
     * @brief Set callback for configuration changes
     * @param callback Function called when user saves new config
     */
    void onConfigChange(ConfigChangeCallback callback);
    
    /**
     * @brief Set callback for getting current configuration
     * @param callback Function that returns current config
     */
    void onConfigGet(ConfigGetCallback callback);
    
    /**
     * @brief Set callback for factory reset
     * @param callback Function called to clear stored credentials
     */
    void onFactoryReset(std::function<void()> callback);
    
    /**
     * @brief Set callback for WiFi reset (clears credentials, stays in AP mode)
     * @param callback Function called to clear WiFi credentials
     * 
     * If not set, WiFi reset will only switch to AP mode without clearing credentials.
     * Set this to the same callback as onFactoryReset to clear credentials on WiFi reset.
     */
    void onWiFiReset(std::function<void()> callback);
    
    /**
     * @brief Set logger for debug output (DEPRECATED)
     * @param logger Ignored - use WML_ENABLE_DEBUG_LOGS instead
     * @deprecated Use compile-time WML_ENABLE_DEBUG_LOGS=0/1 in WMLBuildConfig.h
     */
    void setLogger(void* logger) { (void)logger; /* no-op, use WML_ENABLE_DEBUG_LOGS */ }
    
    /**
     * @brief Set web UI authentication
     * @param username Username (empty = no auth)
     * @param password Password
     */
    void setAuthentication(const String& username, const String& password);
    
    /**
     * @brief Set custom device name shown in UI
     * @param name Device name/title
     */
    void setDeviceName(const String& name);
    
    /**
     * @brief Set firmware version shown in footer
     * @param version Version string
     */
    void setFirmwareVersion(const String& version);
    
    /**
     * @brief Set whether to restart after saving config
     * @param restart true to restart after save (default), false to stay running
     */
    void setRestartAfterSave(bool restart);
    
    // ==================== Extension Points ====================
    // See WMLPortalExtensions.h for the Extension Contract!
    // Max 8 extensions per type. Returns false if registry full.
    
    /**
     * @brief Register a status contributor
     * @param contributor Pointer to contributor (caller owns memory)
     * @return true if registered, false if registry full (max 8)
     * @warning See WMLPortalExtensions.h for contract requirements
     */
    bool addStatusContributor(IStatusContributor* contributor);
    
    /**
     * @brief Register a route registrar
     * @param registrar Pointer to registrar (caller owns memory)
     * @return true if registered, false if registry full (max 8)
     * @note Call BEFORE begin() to ensure routes are registered
     * @warning See WMLPortalExtensions.h for contract requirements
     */
    bool addRouteRegistrar(IRouteRegistrar* registrar);
    
    /**
     * @brief Register a config section provider
     * @param provider Pointer to provider (caller owns memory)
     * @return true if registered, false if registry full (max 8)
     * @warning See WMLPortalExtensions.h for contract requirements
     */
    bool addConfigProvider(IConfigSectionProvider* provider);
    
    /**
     * @brief Register a loop handler
     * @param handler Pointer to handler (caller owns memory)
     * @return true if registered, false if registry full (max 8)
     * @warning Handler MUST NOT block! See WMLPortalExtensions.h
     */
    bool addLoopHandler(ILoopHandler* handler);
    
    // ==================== Lifecycle ====================
    
    /**
     * @brief Initialize and register all web routes
     * 
     * Call this after setting up callbacks
     */
    void begin();
    
    /**
     * @brief Process portal tasks (call in loop)
     * 
     * Handles async network scan results and pending resets
     */
    void loop();
    
    // ==================== Status ====================
    
    /**
     * @brief Check if a client is currently connected to the portal
     * @return true if clients are accessing the portal
     */
    bool hasActiveClients() const;
    
private:
    // ==================== Internal Methods ====================
    
    void registerRoutes();
    
    // Page handlers (GZIP compressed)
    void handleRoot(AsyncWebServerRequest* request);
    void handleWiFiSetup(AsyncWebServerRequest* request);
    void handleStyle(AsyncWebServerRequest* request);   // Both variants
    void handleScript(AsyncWebServerRequest* request);  // Both variants
    
#if WML_PORTAL_VARIANT == WML_PORTAL_ADVANCED
    void handleStatusPage(AsyncWebServerRequest* request);
    void handleStatusJson(AsyncWebServerRequest* request);
#endif
    
    // API handlers
    void handleNetworkList(AsyncWebServerRequest* request);
    void handleNetworkConfig(AsyncWebServerRequest* request);
    void handleSubmitConfig(AsyncWebServerRequest* request);
    void handleCaptivePortal(AsyncWebServerRequest* request);
    void handleNotFound(AsyncWebServerRequest* request);
    
    // Helpers
    bool isAuthenticated(AsyncWebServerRequest* request);
    void sendGzipAsset(AsyncWebServerRequest* request, 
                       const uint8_t* data, size_t len, 
                       const char* contentType, uint32_t cacheSeconds);
    void scheduleRestart(uint32_t delayMs);
    
    void startAsyncScan(bool force = false);
    void collectScanResults();
    
    // ==================== Member Variables ====================
    
    AsyncWebServer& _server;
    WiFiManagerLite& _wifiManager;
    
    ConfigChangeCallback _onConfigChange;
    ConfigGetCallback _onConfigGet;
    std::function<void()> _onFactoryReset;
    std::function<void()> _onWiFiReset;
    
    String _authUser;
    String _authPass;
    String _deviceName;
    bool _deviceNameExplicit = false;
    String _firmwareVersion;
    bool _restartAfterSave;
    
    // Network scan cache (struct-based, no JSON string cache)
    struct ScanNet {
        char ssid[33];      // Max SSID length + null
        char bssid[18];     // "XX:XX:XX:XX:XX:XX" + null
        int8_t rssi;
        uint8_t encrypted;  // 0 = open, 1 = encrypted
    };
    static const uint8_t kMaxScanNets = 20;
    ScanNet _scanCache[kMaxScanNets];
    uint8_t _scanCount;
    bool _scanRunning;
    uint32_t _scanCacheTime;
    static const uint32_t kScanCacheMs = WML_SCAN_CACHE_MS;
    
    // Active client tracking
    mutable uint32_t _lastRequestTime;
    static const uint32_t kClientTimeoutMs = WML_CLIENT_TIMEOUT_MS;
    
    // Pending reset handling
    bool _pendingReset;
    bool _pendingFactoryReset;
    uint32_t _pendingResetTime;
    static const uint32_t kResetDelayMs = 500;
    
    // Extension registries (fixed-size arrays, no heap)
    static const uint8_t kMaxExtensions = 8;
    IStatusContributor* _statusContributors[kMaxExtensions];
    uint8_t _statusContributorCount;
    IRouteRegistrar* _routeRegistrars[kMaxExtensions];
    uint8_t _routeRegistrarCount;
    IConfigSectionProvider* _configProviders[kMaxExtensions];
    uint8_t _configProviderCount;
    ILoopHandler* _loopHandlers[kMaxExtensions];
    uint8_t _loopHandlerCount;
};

} // namespace WML
